"use client";

import { useMemo, useState } from "react";
import { ITEM_CATALOG, RARITY_META, type HeroClass } from "../../lib/game/progression";

export default function InventoryGrid({ heroClass }: { heroClass: HeroClass }) {
  const items = ITEM_CATALOG.filter((item) => item.heroClass === heroClass);
  const [search, setSearch] = useState("");
  const [rarity, setRarity] = useState("ALL");
  const [slot, setSlot] = useState("ALL");
  const filteredItems = useMemo(() => items.filter((item) => (rarity === "ALL" || item.rarity === rarity) && (slot === "ALL" || item.slot === slot) && item.name.toLowerCase().includes(search.toLowerCase())), [items, rarity, search, slot]);
  return <section className="rounded-3xl border border-slate-700 bg-slate-900 p-5 shadow-xl"><div className="flex flex-wrap items-baseline justify-between gap-3"><h2 className="font-mono text-lg font-black text-white">Inventário</h2><span className="text-xs text-slate-400">{filteredItems.length} de 20 itens</span></div><div className="mt-4 grid gap-2 sm:grid-cols-3"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Filtrar por nome..." className="rounded-xl border border-slate-700 bg-slate-800 px-3 py-2 text-sm text-white outline-none focus:border-cyan-300" /><select value={rarity} onChange={(event) => setRarity(event.target.value)} className="rounded-xl border border-slate-700 bg-slate-800 px-3 py-2 text-sm text-white"><option value="ALL">Todas raridades</option>{Object.entries(RARITY_META).map(([key, meta]) => <option key={key} value={key}>{meta.label}</option>)}</select><select value={slot} onChange={(event) => setSlot(event.target.value)} className="rounded-xl border border-slate-700 bg-slate-800 px-3 py-2 text-sm text-white"><option value="ALL">Todos slots</option><option value="weapon">Arma</option><option value="head">Cabeça</option><option value="body">Corpo</option><option value="accessory">Acessório</option></select></div><div className="mt-4 grid grid-cols-4 gap-2 sm:grid-cols-5">{filteredItems.map((item) => <div key={item.id} title={`${item.name} · ${RARITY_META[item.rarity].label}`} className="aspect-square rounded-xl border bg-slate-800 p-2" style={{ borderColor: RARITY_META[item.rarity].color }}><span className="text-lg">{item.slot === "weapon" ? "⚔️" : item.slot === "head" ? "🪖" : item.slot === "body" ? "🥋" : "💍"}</span><p className="mt-1 truncate text-[9px] font-bold text-slate-200">{item.name}</p><p className="text-[8px]" style={{ color: RARITY_META[item.rarity].color }}>{RARITY_META[item.rarity].label}</p></div>)}</div><div className="mt-4 flex flex-wrap gap-3 text-xs">{Object.entries(RARITY_META).map(([key, meta]) => <span key={key} style={{ color: meta.color }}>{meta.label} {meta.chance}</span>)}</div></section>;
}
